config/routes.rb
Rails.application.routes.draw do
  resources :artices
  devise_for :users
  root to: "homes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    
    if user.persisted?
      can :manage, :all
    else
      can :read, :all
      can :create, Artice if user.persisted?
      can :update, Artice do |article|
        article.user_id == user.id
      end
      can :destroy, Artice do |article|
        article.user_id == user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artice.rb
class Artice < ApplicationRecord
	include Timestampbale
	belongs_to :user
	# scope :for_user, ->(user) { where(user: user) }

	validates_presence_of :title, message: "Title Can't be blank!"
end

app/models/concerns/timestampbale.rb
module Timestampbale
	extend ActiveSupport::Concern

	included do
		before_save :update_timestamps
	end

	def update_timestamps
		self.updated_at = Time.current
	end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :artices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/artices_controller.rb
class ArticesController < ApplicationController
  load_and_authorize_resource
  before_action :set_artice, only: %i[ show edit update destroy ]
  # GET /artices or /artices.json
  def index
    @artices = @current_user.artices
  end

  # GET /artices/1 or /artices/1.json
  def show
  end

  # GET /artices/new
  def new
    @artice = Artice.new
  end

  # GET /artices/1/edit
  def edit
  end

  # POST /artices or /artices.json
  def create
    @artice = Artice.new(artice_params) 
    respond_to do |format|
      @artice&.user = current_user 
      if @artice.save
        UserMailer.new_article_notification(@artice).deliver_now
        format.html { redirect_to artice_url(@artice), notice: "Artice was successfully created." }
        format.json { render :show, status: :created, location: @artice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artices/1 or /artices/1.json
  def update
    respond_to do |format|
      if @artice.update(artice_params)
        UserMailer.new_article_notification(@artice).deliver_now
        format.html { redirect_to artice_url(@artice), notice: "Artice was successfully updated." }
        format.json { render :show, status: :ok, location: @artice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artices/1 or /artices/1.json
  def destroy
    @artice.destroy!

    respond_to do |format|
      format.html { redirect_to artices_url, notice: "Artice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artice
      @artice = Artice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artice_params
      params.require(:artice).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artices_helper.rb
module ArticesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/artices/_artice.html.erb
<div id="<%= dom_id artice %>">
  <p>
    <strong>Title:</strong>
    <%= artice.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= artice.body %>
  </p>

</div>

app/views/artices/_form.html.erb
<%= form_with(model: artice) do |form| %>
  <% if artice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artice.errors.count, "error") %> prohibited this artice from being saved:</h2>

      <ul>
        <% artice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artices/edit.html.erb
<h1>Editing artice</h1>

<%= render "form", artice: @artice %>

<br>

<div>
  <%= link_to "Show this artice", @artice %> |
  <%= link_to "Back to artices", artices_path %>
</div>

app/views/artices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artices</h1>

<div id="artices">
  <% @artices.each do |artice| %>
    <%= render artice %>
    <p>
      <%= link_to "Show this artice", artice %>
    </p>
  <% end %>
</div>

<%= link_to "New artice", new_artice_path %>

app/views/artices/new.html.erb
<h1>New artice</h1>

<%= render "form", artice: @artice %>

<br>

<div>
  <%= link_to "Back to artices", artices_path %>
</div>

app/views/artices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artice %>

<div>
  <%= link_to "Edit this artice", edit_artice_path(@artice) %> |
  <%= link_to "Back to artices", artices_path %>

  <%= button_to "Destroy this artice", @artice, method: :delete %>
</div>

app/views/homes/index.html.erb
<div id ="messages"></div>
<input type = "text" id= "message">
<button id = "send">Send</button>

<%if current_user.present?%>
<%=current_user.email%>
<%=button_to "signout", destroy_user_session_path, method: :delete, data: {confirm: "Are you want to sure?"}%>
<%else%>
<%=link_to "signin", new_user_session_path%>
<%end%>

<%=link_to "Articles", artices_path%>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const chatChannel = consumer.subscriptions.create("ChatChannel", {
      received(data) {
        const messages = document.querySelector('#messages')
        messages.insertAdjacentHTML('beforeend', `<p>${data.message}</p>`)
      }
    })

    document.querySelector('#send').addEventListener('click', () => {
      const input = document.querySelector('#message')
      chatChannel.speak(input.value)
      input.value = ''
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>